synadia-io/helm-charts

charts/helix/Chart.yaml
charts/helix/files/deployment.yaml
charts/helix/files/secrets.yaml
charts/helix/templates/_helpers.tpl
charts/helix/templates/deployment.yaml
charts/helix/templates/secrets.yaml
charts/helix/values.yaml

- Added configmap and secret checksum annotations to deployment
- Updates secret naming scheme to reduce chance of conflict

Checksums and secret names

---

charts/control-plane/docs-sync.yaml

[control-plane] fix docs sync dest

---

charts/control-plane/Chart.yaml
charts/control-plane/values.yaml

0.2.0 release

---

charts/control-plane/Chart.yaml
charts/control-plane/test/defaults_test.go
charts/control-plane/values.yaml

1.0.0 release

---

charts/control-plane/Chart.yaml
charts/control-plane/README.md
charts/control-plane/values.yaml

[control plane] release 1.1.0

---

charts/synadia-server/files/stateful-set/nats-container.yaml
charts/synadia-server/test/tls_test.go

pull in changes from https://github.com/nats-io/k8s/pull/806

[synadia-server] set probe scheme based on monitor tls

---

charts/control-plane/Chart.yaml
charts/control-plane/values.yaml

Upgrade Control Plane to 1.1.1

[control-plane] upgrade to 1.1.1

---

charts/synadia-server/Chart.yaml
charts/synadia-server/values.yaml

release synadia-server 1.0.1

---

charts/synadia-server/Chart.yaml
charts/synadia-server/values.yaml

release synadia-server 1.0.2

---

charts/synadia-server/Chart.yaml
charts/synadia-server/values.yaml

[synadia-server] release 1.0.3

---

charts/synadia-server/Chart.yaml
charts/synadia-server/values.yaml

[synadia-server] release 1.1.0

---

charts/control-plane/Chart.yaml
charts/control-plane/values.yaml

[control-plane] upgrade to 1.1.2

---

charts/synadia-server/Chart.yaml
charts/synadia-server/values.yaml

Upgrade synadia-server to 1.1.1

[synadia-server] upgrade to 1.1.1

---

charts/control-plane/Chart.yaml
charts/control-plane/values.yaml

[control-plane] release 1.2.0

---

charts/synadia-server/Chart.yaml
charts/synadia-server/values.yaml

[synadia-server] release 1.1.2

---

charts/control-plane/Chart.yaml
charts/control-plane/values.yaml

[control-plane] release 1.2.1

---

charts/synadia-server/Chart.yaml
charts/synadia-server/README.md
charts/synadia-server/files/nats-box/deployment/pod-template.yaml
charts/synadia-server/files/pod-monitor.yaml
charts/synadia-server/files/stateful-set/pod-template.yaml
charts/synadia-server/files/stateful-set/prom-exporter-container.yaml
charts/synadia-server/templates/_helpers.tpl
charts/synadia-server/templates/pod-monitor.yaml
charts/synadia-server/test/chart_test.go
charts/synadia-server/test/defaults_test.go
charts/synadia-server/test/go.mod
charts/synadia-server/test/go.sum
charts/synadia-server/test/resources_test.go
charts/synadia-server/values.yaml

Resolves #40 
Add `promExporter` option to match `nats` Helm Chart

[synadia-server] add promExporter option

---

charts/synadia-server/Chart.yaml
charts/synadia-server/values.yaml

Upgrade synadia-server to 1.1.4

[synadia-server] upgrade to 1.1.4

---

charts/synadia-server/Chart.yaml
charts/synadia-server/values.yaml

upgrade synadia-server to 1.1.6

[synadia-server] upgrade to 1.1.6

---

charts/synadia-server/Chart.yaml
charts/synadia-server/values.yaml

upgrade synadia-server to 1.1.7

[synadia-server] upgrade to 1.1.7

---

charts/synadia-server/Chart.yaml
charts/synadia-server/values.yaml

[synadia-server] upgrade to 1.1.8

---

charts/control-plane/Chart.yaml
charts/control-plane/values.yaml

upgrade `control-plane` to 1.3.1

[control-plane] upgrade to 1.3.1

---

charts/synadia-server/Chart.yaml
charts/synadia-server/values.yaml

upgrade synadia-server to 1.1.9

[synadia-server] upgrade to 1.1.9

---

charts/synadia-server/Chart.yaml
charts/synadia-server/README.md
charts/synadia-server/values.yaml

[synadia-server] upgrade to 1.1.10

---

charts/control-plane/Chart.yaml
charts/control-plane/values.yaml

upgrade control-plane to 1.4.0

[control-plane] upgrade to 1.4.0

---

charts/control-plane/Chart.yaml
charts/control-plane/values.yaml

upgrade control-plane to 1.4.1

[control-plane] upgrade to 1.4.1

---

charts/control-plane/Chart.yaml
charts/control-plane/values.yaml

upgrade control-plane to 1.4.2

[control-plane] upgrade to 1.4.2
